{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "1b525699-a0da-44f1-b038-24dd32ca0fc5",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Received b'Welcome to the server!\\n'\n",
      "Received b'Welcome to the server!\\n'\n",
      "Received b'Welcome to the server!\\n'\n",
      "Received b'Welcome to the server!\\n'\n",
      "Received b'Welcome to the server!\\n'\n",
      "Received b'Welcome to the server!\\n'\n",
      "Received b'Welcome to the server!\\n'\n",
      "Received b'Welcome to the server!\\n'\n",
      "Received b'Welcome to the server!\\n'\n",
      "Received b'Welcome to the server!\\n'\n",
      "Received b'Welcome to the server!\\n'\n",
      "Received b'Welcome to the server!\\n'\n",
      "Received b'Welcome to the server!\\n'\n",
      "Received b'Welcome to the server!\\n'\n",
      "Received b'Welcome to the server!\\n'\n",
      "Received b'Welcome to the server!\\n'\n",
      "Received b'Welcome to the server!\\n'\n",
      "Received b'Welcome to the server!\\n'\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread Exception in thread Thread-1081 (connect_to_server):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "Exception in thread Thread-1078 (connect_to_server):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "Exception in thread Thread-1107 (connect_to_server):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "Exception in thread Thread-1103 (connect_to_server):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "Exception in thread Thread-1029 (connect_to_server):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "Exception in thread Thread-1028 (connect_to_server):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "Exception in thread Thread-1053 (connect_to_server):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "Exception in thread Thread-1056 (connect_to_server):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "Exception in thread Thread-1087 (connect_to_server):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "Exception in thread Thread-1089 (connect_to_server):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "Exception in thread Thread-1088 (connect_to_server):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "Exception in thread Thread-1086 (connect_to_server):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "Exception in thread Thread-1085 (connect_to_server):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "Exception in thread Thread-1084 (connect_to_server):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "Exception in thread Thread-1083 (connect_to_server):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "Exception in thread Thread-1082 (connect_to_server):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "Exception in thread Thread-1077 (connect_to_server):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "Exception in thread Thread-1063 (connect_to_server):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "Exception in thread Thread-1072 (connect_to_server):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "Exception in thread Thread-1075 (connect_to_server):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "Exception in thread Thread-1030 (connect_to_server):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "Exception in thread Thread-1031 (connect_to_server):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "Exception in thread Thread-1032 (connect_to_server):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "Exception in thread Thread-1045 (connect_to_server):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "Exception in thread Thread-1046 (connect_to_server):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "Exception in thread Thread-1047 (connect_to_server):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "Exception in thread Thread-1049 (connect_to_server):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "Exception in thread Thread-1052 (connect_to_server):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "Exception in thread Thread-1054 (connect_to_server):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "Exception in thread Thread-1080 (connect_to_server):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "Exception in thread Thread-1069 (connect_to_server):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "Exception in thread Thread-1106 (connect_to_server):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "Exception in thread Thread-1073 (connect_to_server):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "Exception in thread Thread-1076 (connect_to_server):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "Exception in thread Thread-1102 (connect_to_server):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "Exception in thread Thread-1070 (connect_to_server):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "Exception in thread Thread-1067 (connect_to_server):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "Exception in thread Thread-1071 (connect_to_server):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "Exception in thread Thread-1066 (connect_to_server):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "Exception in thread Thread-1051 (connect_to_server):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "Exception in thread Thread-1104 (connect_to_server):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "Exception in thread Thread-1105 (connect_to_server):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "Exception in thread Thread-1033 (connect_to_server):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "Exception in thread Thread-1034 (connect_to_server):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "Exception in thread Thread-1035 (connect_to_server):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "Exception in thread Thread-1036 (connect_to_server):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "Exception in thread Thread-1037 (connect_to_server):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "Exception in thread Thread-1038 (connect_to_server):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "Exception in thread Thread-1057 (connect_to_server):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "Exception in thread Thread-1060 (connect_to_server):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "Exception in thread Thread-1101 (connect_to_server):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "Exception in thread Thread-1108 (connect_to_server):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "Exception in thread Thread-1090 (connect_to_server):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "Exception in thread Thread-1091 (connect_to_server):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "Exception in thread Thread-1092 (connect_to_server):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "Exception in thread Thread-1093 (connect_to_server):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "Exception in thread Thread-1094 (connect_to_server):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "Exception in thread Thread-1095 (connect_to_server):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "Exception in thread Thread-1096 (connect_to_server):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "Exception in thread Thread-1097 (connect_to_server):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "Exception in thread Thread-1098 (connect_to_server):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "Exception in thread Thread-1099 (connect_to_server):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "Exception in thread Thread-1100 (connect_to_server):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "Exception in thread Thread-1044 (connect_to_server):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "Exception in thread Thread-1041 (connect_to_server):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "Exception in thread Thread-1039 (connect_to_server):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "Exception in thread Thread-1043 (connect_to_server):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "Exception in thread Thread-1042 (connect_to_server):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "Exception in thread Thread-1064 (connect_to_server):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "Exception in thread Thread-1050 (connect_to_server):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "Exception in thread Thread-1058 (connect_to_server):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "Exception in thread Thread-1062 (connect_to_server):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "Exception in thread Thread-1048 (connect_to_server):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "Exception in thread Thread-1055 (connect_to_server):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "Exception in thread Thread-1068 (connect_to_server):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "Exception in thread Thread-1065 (connect_to_server):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "Exception in thread Thread-1061 (connect_to_server):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "Exception in thread Thread-1040 (connect_to_server):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "Thread-1027 (connect_to_server):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "Exception in thread Thread-1059 (connect_to_server):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "Exception in thread Thread-1079 (connect_to_server):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    self.run()\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    self.run()\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    self.run()\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    self.run()\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "Exception in thread Thread-1074 (connect_to_server):\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1073, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    self.run()\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    self.run()\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    self.run()\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    self.run()\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    self.run()\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    self.run()\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    self.run()\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    self.run()\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    self.run()\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    self.run()\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    self.run()\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    self.run()\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    self.run()\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    self.run()\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    self.run()\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    self.run()\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    self.run()\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    self.run()\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    self.run()\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    self.run()\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    self.run()\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    self.run()\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    self.run()\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    self.run()\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    self.run()\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    self.run()\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    self.run()\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    self.run()\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    self.run()\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    self.run()\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    self.run()\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    self.run()\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    self.run()\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1010, in run\n",
      "    self.run()\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    self.run()\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    self.run()\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    self.run()\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1010, in run\n",
      "    self.run()\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    self.run()\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    self.run()\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    self.run()\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    self.run()\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1010, in run\n",
      "    self.run()\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    self.run()\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    self.run()\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    self.run()\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    self.run()\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    self.run()\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    self.run()\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    self.run()\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    self.run()\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    self.run()\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    self.run()\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    self.run()\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1010, in run\n",
      "    self.run()\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1010, in run\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1010, in run\n",
      "    self.run()\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    self.run()\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    self.run()\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    self.run()\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1010, in run\n",
      "    self.run()\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    self.run()\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    self.run()\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    self.run()\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    self.run()\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    self.run()\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    self.run()\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1010, in run\n",
      "    self.run()\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    self.run()\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    self.run()\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1010, in run\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1010, in run\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1010, in run\n",
      "    self.run()\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1010, in run\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1010, in run\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1010, in run\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1010, in run\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1010, in run\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1010, in run\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1010, in run\n",
      "    self.run()\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1010, in run\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1010, in run\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Temp\\ipykernel_4036\\1715424069.py\", line 8, in connect_to_server\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1010, in run\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1010, in run\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1010, in run\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1010, in run\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1010, in run\n",
      "    self.run()\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    self.run()\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1010, in run\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1010, in run\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1010, in run\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1010, in run\n",
      "    self.run()\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 766, in run_closure\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1010, in run\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1010, in run\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1010, in run\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1010, in run\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1010, in run\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1010, in run\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1010, in run\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1010, in run\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1010, in run\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1010, in run\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1010, in run\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1010, in run\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1010, in run\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1010, in run\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1010, in run\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1010, in run\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1010, in run\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1010, in run\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1010, in run\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1010, in run\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1010, in run\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Temp\\ipykernel_4036\\1715424069.py\", line 8, in connect_to_server\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1010, in run\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1010, in run\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Temp\\ipykernel_4036\\1715424069.py\", line 8, in connect_to_server\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1010, in run\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1010, in run\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1010, in run\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1010, in run\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1010, in run\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1010, in run\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1010, in run\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1010, in run\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1010, in run\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Temp\\ipykernel_4036\\1715424069.py\", line 8, in connect_to_server\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1010, in run\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1010, in run\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Temp\\ipykernel_4036\\1715424069.py\", line 8, in connect_to_server\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Temp\\ipykernel_4036\\1715424069.py\", line 8, in connect_to_server\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Temp\\ipykernel_4036\\1715424069.py\", line 8, in connect_to_server\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Temp\\ipykernel_4036\\1715424069.py\", line 8, in connect_to_server\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1010, in run\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Temp\\ipykernel_4036\\1715424069.py\", line 8, in connect_to_server\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1010, in run\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1010, in run\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1010, in run\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Temp\\ipykernel_4036\\1715424069.py\", line 8, in connect_to_server\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Temp\\ipykernel_4036\\1715424069.py\", line 8, in connect_to_server\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1010, in run\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Temp\\ipykernel_4036\\1715424069.py\", line 8, in connect_to_server\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Temp\\ipykernel_4036\\1715424069.py\", line 8, in connect_to_server\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Temp\\ipykernel_4036\\1715424069.py\", line 8, in connect_to_server\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Temp\\ipykernel_4036\\1715424069.py\", line 8, in connect_to_server\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Temp\\ipykernel_4036\\1715424069.py\", line 8, in connect_to_server\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Temp\\ipykernel_4036\\1715424069.py\", line 8, in connect_to_server\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Temp\\ipykernel_4036\\1715424069.py\", line 8, in connect_to_server\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Temp\\ipykernel_4036\\1715424069.py\", line 8, in connect_to_server\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Temp\\ipykernel_4036\\1715424069.py\", line 8, in connect_to_server\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Temp\\ipykernel_4036\\1715424069.py\", line 8, in connect_to_server\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Temp\\ipykernel_4036\\1715424069.py\", line 8, in connect_to_server\n",
      "    _threading_Thread_run(self)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\threading.py\", line 1010, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Temp\\ipykernel_4036\\1715424069.py\", line 8, in connect_to_server\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Temp\\ipykernel_4036\\1715424069.py\", line 8, in connect_to_server\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Temp\\ipykernel_4036\\1715424069.py\", line 8, in connect_to_server\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Temp\\ipykernel_4036\\1715424069.py\", line 8, in connect_to_server\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Temp\\ipykernel_4036\\1715424069.py\", line 8, in connect_to_server\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Temp\\ipykernel_4036\\1715424069.py\", line 8, in connect_to_server\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Temp\\ipykernel_4036\\1715424069.py\", line 8, in connect_to_server\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Temp\\ipykernel_4036\\1715424069.py\", line 8, in connect_to_server\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Temp\\ipykernel_4036\\1715424069.py\", line 8, in connect_to_server\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Temp\\ipykernel_4036\\1715424069.py\", line 8, in connect_to_server\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Temp\\ipykernel_4036\\1715424069.py\", line 8, in connect_to_server\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Temp\\ipykernel_4036\\1715424069.py\", line 8, in connect_to_server\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Temp\\ipykernel_4036\\1715424069.py\", line 8, in connect_to_server\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Temp\\ipykernel_4036\\1715424069.py\", line 8, in connect_to_server\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Temp\\ipykernel_4036\\1715424069.py\", line 8, in connect_to_server\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Temp\\ipykernel_4036\\1715424069.py\", line 8, in connect_to_server\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Temp\\ipykernel_4036\\1715424069.py\", line 8, in connect_to_server\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Temp\\ipykernel_4036\\1715424069.py\", line 8, in connect_to_server\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Temp\\ipykernel_4036\\1715424069.py\", line 8, in connect_to_server\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Temp\\ipykernel_4036\\1715424069.py\", line 8, in connect_to_server\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Temp\\ipykernel_4036\\1715424069.py\", line 8, in connect_to_server\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Temp\\ipykernel_4036\\1715424069.py\", line 8, in connect_to_server\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Temp\\ipykernel_4036\\1715424069.py\", line 8, in connect_to_server\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Temp\\ipykernel_4036\\1715424069.py\", line 8, in connect_to_server\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Temp\\ipykernel_4036\\1715424069.py\", line 8, in connect_to_server\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Temp\\ipykernel_4036\\1715424069.py\", line 8, in connect_to_server\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Temp\\ipykernel_4036\\1715424069.py\", line 8, in connect_to_server\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Temp\\ipykernel_4036\\1715424069.py\", line 8, in connect_to_server\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Temp\\ipykernel_4036\\1715424069.py\", line 8, in connect_to_server\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Temp\\ipykernel_4036\\1715424069.py\", line 8, in connect_to_server\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Temp\\ipykernel_4036\\1715424069.py\", line 8, in connect_to_server\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Temp\\ipykernel_4036\\1715424069.py\", line 8, in connect_to_server\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Temp\\ipykernel_4036\\1715424069.py\", line 8, in connect_to_server\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Temp\\ipykernel_4036\\1715424069.py\", line 8, in connect_to_server\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Temp\\ipykernel_4036\\1715424069.py\", line 8, in connect_to_server\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Temp\\ipykernel_4036\\1715424069.py\", line 8, in connect_to_server\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Temp\\ipykernel_4036\\1715424069.py\", line 8, in connect_to_server\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Temp\\ipykernel_4036\\1715424069.py\", line 8, in connect_to_server\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Temp\\ipykernel_4036\\1715424069.py\", line 8, in connect_to_server\n",
      "        self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Temp\\ipykernel_4036\\1715424069.py\", line 8, in connect_to_server\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Temp\\ipykernel_4036\\1715424069.py\", line 8, in connect_to_server\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Temp\\ipykernel_4036\\1715424069.py\", line 8, in connect_to_server\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Temp\\ipykernel_4036\\1715424069.py\", line 8, in connect_to_server\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Temp\\ipykernel_4036\\1715424069.py\", line 8, in connect_to_server\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Temp\\ipykernel_4036\\1715424069.py\", line 8, in connect_to_server\n",
      "self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Temp\\ipykernel_4036\\1715424069.py\", line 8, in connect_to_server\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Temp\\ipykernel_4036\\1715424069.py\", line 8, in connect_to_server\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Temp\\ipykernel_4036\\1715424069.py\", line 8, in connect_to_server\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Temp\\ipykernel_4036\\1715424069.py\", line 8, in connect_to_server\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Temp\\ipykernel_4036\\1715424069.py\", line 8, in connect_to_server\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Temp\\ipykernel_4036\\1715424069.py\", line 8, in connect_to_server\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Temp\\ipykernel_4036\\1715424069.py\", line 8, in connect_to_server\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Temp\\ipykernel_4036\\1715424069.py\", line 8, in connect_to_server\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Temp\\ipykernel_4036\\1715424069.py\", line 8, in connect_to_server\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Temp\\ipykernel_4036\\1715424069.py\", line 8, in connect_to_server\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Temp\\ipykernel_4036\\1715424069.py\", line 8, in connect_to_server\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Temp\\ipykernel_4036\\1715424069.py\", line 8, in connect_to_server\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Temp\\ipykernel_4036\\1715424069.py\", line 8, in connect_to_server\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Temp\\ipykernel_4036\\1715424069.py\", line 8, in connect_to_server\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"C:\\Users\\kdhome\\AppData\\Local\\Temp\\ipykernel_4036\\1715424069.py\", line 8, in connect_to_server\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n",
      "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host\n"
     ]
    }
   ],
   "source": [
    "import socket\n",
    "import threading\n",
    "\n",
    "def connect_to_server():\n",
    "    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:\n",
    "        s.connect(('127.0.0.1', 8080))\n",
    "        s.sendall(b'Hello, server')\n",
    "        data = s.recv(1024)\n",
    "        print('Received', repr(data))\n",
    "\n",
    "# Create multiple threads to simulate multiple clients\n",
    "for i in range(100):  # Number of concurrent clients\n",
    "    threading.Thread(target=connect_to_server).start()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "3ecd0ac3-2a04-4b3c-bee7-cb9a33c7c2f7",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
